### ISSUE TITLE
Question about building a project

### ISSUE THREAD

**Issue by Ingenu1ty** [HCaseira/lowder_flutter#2]
Hello there🖖 I'm new to flutter, so low-code tools like this are much needed for people like me! Thanks for your efforts!

But I have a question: it looks like the editor and other related stuff goes into the release version of the app as well...? if so, it would be great to have an option to compile the project without the editor and all the extra stuff.

**Comment by HCaseira** [comment]
Hello,

Yes, like with any other library or package, there will be classes or other objects you'll never use but will be included in the build. And you are right, there are classes in the Lowder package that are only used to interact with the editor that will be included in the build. But I don't think it will add much to the size of your project.

If you are referring to the http server or the editor itself, rest assured those won't be included in the build as they are in the 'bin' folder, reserved for any command line tools which a package may wish to make available.

Thank you for using Lowder and give feedback.
Let me know if you need help with something or what you'd like to see an example of.
Regards.

**Comment by Ingenu1ty** [comment]
> Let me know if you need help with something or what you'd like to see an example of

It would be interesting to see an example using advanced state management. Using [this package](https://pub.dev/packages/flutter_riverpod) or something similar...(I'm just starting to explore the flutter ecosystem but want to start with best practices :-)

Also it would be great to have tools in the editor for advanced state management in a low-code approach.... I mean something that would be like [Cosmos](https://reactcosmos.org/) for react.

**Comment by Ingenu1ty** [comment]
I would also suggest adding some features from [that project](https://github.com/5hirish/quinine) to your editor. (Unfortunately, it looks like its repo is no longer updated😔 But useful features and ideas could be developed in other projects😉)

**Comment by Ingenu1ty** [comment]
The original question has been answered, so perhaps I should close this issue to keep issues organized by topic ;-)
