### ISSUE TITLE
I can't run this. I see an eternal spinner: "Waiting for Flutter client to start"

### ISSUE THREAD

**Issue by AbstractClass232** [HCaseira/lowder_flutter#3]
There are also warnings in the console:
`Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:46: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.`

Maybe they are the reason?...

**Comment by HCaseira** [comment]
Hi, thanks for noticing.
I've now fixed the web project in the `examples` folder.
If you're having this issue in your own project, simply delete the `web` folder and run `flutter create --platforms web .` to fix it.

**Comment by AbstractClass232** [comment]
thanks, it works now.
