### ISSUE TITLE
Doesn't work if the server is running on a remote machine

### ISSUE THREAD

**Issue by Ingenu1ty** [HCaseira/lowder_flutter#7]
Everything is fine if you run it locally, but if you run it on a remote computer, then `some_ip:8787/editor.html` the editor endlessly displays the message: `Waiting for Flutter client to start.`

Why so strange behavior? Wouldn't it be better to be able to use the editor on a remote computer too?

**Comment by HCaseira** [comment]
I'll look into it.

**Comment by HCaseira** [comment]
The last commit introduces a new argument to start the Lowder Editor.
You can now start it as follows: `dart run lowder -a 192.168.1.7 -p 5445`.

**Comment by Ingenu1ty** [comment]
Thanks, the new CLI argument works, but the output is a little wrong:
`Serving at http://0.0.0.0:8787
Open Editor at http://some_ip:8787/editor.html`

I think this should be:
`Serving at http://some_ip:8787
Open Editor at http://some_ip:8787/editor.html` 

not a big deal, of course, I just noted it here...
